<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{0E7A7AE5-0D9D-4608-A959-FD0C90E06841}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>SolidEdge.Community</RootNamespace>
    <AssemblyName>SolidEdge.Community</AssemblyName>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>bin\Release\SolidEdge.Community.XML</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Interop.SolidEdge, Version=106.8.1.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\packages\Interop.SolidEdge.106.8.1\lib\net40\Interop.SolidEdge.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AddIn\EdgeBarControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="AddIn\EdgeBarController.cs" />
    <Compile Include="AddIn\EdgeBarPage.cs" />
    <Compile Include="AddIn\EdgeBarPageAttribute.cs" />
    <Compile Include="AddIn\ExtensionMethods.cs" />
    <Compile Include="AddIn\NativeResourceAttribute.cs" />
    <Compile Include="AddIn\Overlay.cs" />
    <Compile Include="AddIn\OverlayController.cs" />
    <Compile Include="AddIn\Ribbon.cs" />
    <Compile Include="AddIn\RibbonControl.cs" />
    <Compile Include="AddIn\RibbonController.cs" />
    <Compile Include="AddIn\RibbonGroup.cs" />
    <Compile Include="AddIn\RibbonTab.cs" />
    <Compile Include="AddIn\SolidEdgeAddIn.cs" />
    <Compile Include="ConnectionPointController.cs" />
    <Compile Include="OleMessageFilter.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="SolidEdgeFramework\Extensions\ApplicationExtensions.cs" />
    <Compile Include="SolidEdgeFramework\Extensions\DocumentsExtensions.cs" />
    <Compile Include="SolidEdgeFramework\Extensions\EnvironmentExtensions.cs" />
    <Compile Include="SolidEdgeFramework\Extensions\RefPlanesExtensions.cs" />
    <Compile Include="SolidEdgeFramework\Extensions\WindowExtensions.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>